<a href="https://colab.research.google.com/github/tanya172/Python/blob/main/numpy_tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
c = np.array([(1,2,3),(4,5,6)],dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


initial placeholder in numpy arrays


In [6]:
x= np.zeros((4,5))
print(x);

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
x = np.full((2,3),7)
print(x)

[[7 7 7]
 [7 7 7]]
